##  Importing Libraries

In [156]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import scale
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn import metrics
from sklearn.metrics import mean_squared_error
from sklearn import preprocessing

In [157]:
df=pd.read_csv('dataset.csv')

In [158]:
df.head()

,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,...,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
0,BU79786,Washington,2763.519279,No,Basic,Bachelor,2/24/2011,Employed,F,56274,...,5,0,1,Corporate Auto,Corporate L3,Offer1,Agent,384.811147,Two-Door Car,Medsize
1,QZ44356,Arizona,6979.535903,No,Extended,Bachelor,1/31/2011,Unemployed,F,0,...,42,0,8,Personal Auto,Personal L3,Offer3,Agent,1131.464935,Four-Door Car,Medsize
2,AI49188,Nevada,12887.431650,No,Premium,Bachelor,2/19/2011,Employed,F,48767,...,38,0,2,Personal Auto,Personal L3,Offer1,Agent,566.472247,Two-Door Car,Medsize
3,WW63253,California,7645.861827,No,Basic,Bachelor,1/20/2011,Unemployed,M,0,...,65,0,7,Corporate Auto,Corporate L2,Offer1,Call Center,529.881344,SUV,Medsize
4,HB64268,Washington,2813.692575,No,Basic,Bachelor,2/3/2011,Employed,M,43836,...,44,0,1,Personal Auto,Personal L1,Offer1,Agent,138.130879,Four-Door Car,Medsize

In [159]:
df.columns

Index(['Customer', 'State', 'Customer Lifetime Value', 'Response', 'Coverage',
       'Education', 'Effective To Date', 'EmploymentStatus', 'Gender',
       'Income', 'Location Code', 'Marital Status', 'Monthly Premium Auto',
       'Months Since Last Claim', 'Months Since Policy Inception',
       'Number of Open Complaints', 'Number of Policies', 'Policy Type',
       'Policy', 'Renew Offer Type', 'Sales Channel', 'Total Claim Amount',
       'Vehicle Class', 'Vehicle Size'],
      dtype='object')

In [160]:
for i in df.columns:
    print(i," ", len(df[i].unique()))

Customer   9134
State   5
Customer Lifetime Value   8041
Response   2
Coverage   3
Education   5
Effective To Date   59
EmploymentStatus   5
Gender   2
Income   5694
Location Code   3
Marital Status   3
Monthly Premium Auto   202
Months Since Last Claim   36
Months Since Policy Inception   100
Number of Open Complaints   6
Number of Policies   9
Policy Type   3
Policy   9
Renew Offer Type   4
Sales Channel   4
Total Claim Amount   5106
Vehicle Class   6
Vehicle Size   3

In [161]:
for i in df.columns:
    print(i, " " , sum(df[i].isnull()))

Customer   0
State   0
Customer Lifetime Value   0
Response   0
Coverage   0
Education   0
Effective To Date   0
EmploymentStatus   0
Gender   0
Income   0
Location Code   0
Marital Status   0
Monthly Premium Auto   0
Months Since Last Claim   0
Months Since Policy Inception   0
Number of Open Complaints   0
Number of Policies   0
Policy Type   0
Policy   0
Renew Offer Type   0
Sales Channel   0
Total Claim Amount   0
Vehicle Class   0
Vehicle Size   0

In [162]:
df.dtypes

Customer                          object
State                             object
Customer Lifetime Value          float64
Response                          object
Coverage                          object
Education                         object
Effective To Date                 object
EmploymentStatus                  object
Gender                            object
Income                             int64
Location Code                     object
Marital Status                    object
Monthly Premium Auto               int64
Months Since Last Claim            int64
Months Since Policy Inception      int64
Number of Open Complaints          int64
Number of Policies                 int64
Policy Type                       object
Policy                            object
Renew Offer Type                  object
Sales Channel                     object
Total Claim Amount               float64
Vehicle Class                     object
Vehicle Size                      object
dtype: object

In [163]:
y = df.iloc[:,2]
x = df
y.head()

0     2763.519279
1     6979.535903
2    12887.431650
3     7645.861827
4     2813.692575
Name: Customer Lifetime Value, dtype: float64

## Feature Engineering

In [164]:
New_parameter = np.array(x['Customer'])
for i in range(len(New_parameter)):
    New_parameter[i] = New_parameter[i][0:2]
x['New Parameter'] = New_parameter

temp = x.groupby('New Parameter')['Customer Lifetime Value'].mean()

In [165]:
clv_by_id = np.array(range(x.shape[0]))
clv_by_id = clv_by_id.astype(float)
for i in range(x.shape[0]) :
    clv_by_id[i] = temp[x['New Parameter'][i]]
x['Average ID'] = clv_by_id

In [166]:
x['Present Value'] = x['Monthly Premium Auto'] * x['Months Since Policy Inception'] - x['Total Claim Amount']

In [167]:
x = df.drop(['Customer Lifetime Value','Gender','Customer','State'], axis = 1 )

## Data Pre-Processing

In [168]:
xx = pd.get_dummies(x)

In [169]:
x.head()

,Response,Coverage,Education,Effective To Date,EmploymentStatus,Income,Location Code,Marital Status,Monthly Premium Auto,Months Since Last Claim,...,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,New Parameter,Average ID,Present Value
0,No,Basic,Bachelor,2/24/2011,Employed,56274,Suburban,Married,69,32,...,Corporate Auto,Corporate L3,Offer1,Agent,384.811147,Two-Door Car,Medsize,BU,8448.636743,-39.811147
1,No,Extended,Bachelor,1/31/2011,Unemployed,0,Suburban,Single,94,13,...,Personal Auto,Personal L3,Offer3,Agent,1131.464935,Four-Door Car,Medsize,QZ,11301.879265,2816.535065
2,No,Premium,Bachelor,2/19/2011,Employed,48767,Suburban,Married,108,18,...,Personal Auto,Personal L3,Offer1,Agent,566.472247,Two-Door Car,Medsize,AI,12840.560422,3537.527753
3,No,Basic,Bachelor,1/20/2011,Unemployed,0,Suburban,Married,106,18,...,Corporate Auto,Corporate L2,Offer1,Call Center,529.881344,SUV,Medsize,WW,8067.916713,6360.118656
4,No,Basic,Bachelor,2/3/2011,Employed,43836,Rural,Single,73,12,...,Personal Auto,Personal L1,Offer1,Agent,138.130879,Four-Door Car,Medsize,HB,10619.413848,3073.869121

In [170]:
xx

,Income,Monthly Premium Auto,Months Since Last Claim,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Total Claim Amount,Average ID,Present Value,Response_No,...,New Parameter_ZQ,New Parameter_ZR,New Parameter_ZS,New Parameter_ZT,New Parameter_ZU,New Parameter_ZV,New Parameter_ZW,New Parameter_ZX,New Parameter_ZY,New Parameter_ZZ
0,56274,69,32,5,0,1,384.811147,8448.636743,-39.811147,1,...,0,0,0,0,0,0,0,0,0,0
1,0,94,13,42,0,8,1131.464935,11301.879265,2816.535065,1,...,0,0,0,0,0,0,0,0,0,0
2,48767,108,18,38,0,2,566.472247,12840.560422,3537.527753,1,...,0,0,0,0,0,0,0,0,0,0
3,0,106,18,65,0,7,529.881344,8067.916713,6360.118656,1,...,0,0,0,0,0,0,0,0,0,0
4,43836,73,12,44,0,1,138.130879,10619.413848,3073.869121,1,...,0,0,0,0,0,0,0,0,0,0
5,62902,69,14,94,0,2,159.383042,6338.902021,6326.616958,0,...,0,0,0,0,0,0,0,0,0,0
6,55350,67,0,13,0,9,321.600000,10453.283066,549.400000,0,...,0,0,0,0,0,0,0,0,0,0
7,0,101,0,68,0,4,363.029680,5494.157323,6504.970320,1,...,0,0,0,0,0,0,0,0,0,0
8,14072,71,13,3,0,2,511.200000,7701.493783,-298.200000,0,...,0,0,0,0,0,0,0,0,0,0
9,28812,93,17,7,0,8,425.527834,9498.994949,225.472166,1,...,0,0,0,0,0,0,0,0,0,0
10,0,67,23,5,0,3,482.400000,7148.000438,-147.400000,1,...,0,0,0,0,0,0,0,0,0,0
11,0,110,27,87,0,3,528.000000,9442.271042,9042.000000,1,...,0,0,0,0,0,0,0,0,0,0
12,77026,110,9,82,2,3,472.029737,9922.527333,8547.970263,1,...,0,0,0,0,0,0,0,0,0,0
13,99845,110,23,25,1,8,528.000000,6365.319515,2222.000000,0,...,0,0,0,0,0,0,0,0,0,0
14,83689,70,21,10,2,8,307.139132,5697.858861,392.860868,1,...,0,0,0,0,0,0,0,0,0,0
15,24599,64,12,50,1,2,42.920271,7792.334105,3157.079729,1,...,0,0,0,0,0,0,0,0,0,0
16,25049,67,14,7,0,1,454.245098,9003.875651,14.754902,1,...,0,0,0,0,0,0,0,0,0,0
17,28855,101,12,59,0,1,647.442031,5005.908887,5311.557969,1,...,0,0,0,0,0,0,0,0,0,0
18,51148,72,9,1,0,7,308.981664,7245.712913,-236.981664,1,...,0,0,0,0,0,0,0,0,0,0
19,66140,101,11,21,0,3,484.800000,7393.942005,1636.200000,1,...,0,0,0,0,0,0,0,0,0,0
20,57749,74,31,21,0,1,355.200000,9230.975276,1198.800000,1,...,0,0,0,0,0,0,0,0,0,0
21,13789,79,8,49,0,1,379.200000,9030.982070,3491.800000,1,...,0,0,0,0,0,0,0,0,0,0
22,14072,71,13,3,0,2,511.200000,7710.362220,-298.200000,0,...,0,0,0,0,0,0,0,0,0,0
23,0,73,4,44,3,1,554.376763,5849.701041,2657.623237,1,...,0,0,0,0,0,0,0,0,0,0
24,17870,61,30,91,0,1,439.200000,6979.745606,5111.800000,1,...,0,0,0,0,0,0,0,0,0,0
25,97541,72,22,1,0,3,389.185006,5406.170110,-317.185006,1,...,0,0,0,0,0,0,0,0,0,0
26,0,111,15,47,0,1,799.200000,11299.847528,4417.800000,1,...,0,0,0,0,0,0,0,0,0,0
27,10511,139,33,64,0,1,516.237951,6869.791652,8379.762049,1,...,0,0,0,0,0,0,0,0,0,0
28,86584,111,33,54,2,2,532.800000,7127.152988,5461.200000,1,...,0,0,0,0,0,0,0,0,0,0
29,75690,80,17,44,1,1,384.000000,5739.166512,3136.000000,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9104,57023,67,11,59,0,1,250.652309,6033.495368,3702.347691,1,...,0,0,0,0,0,0,0,0,0,0
9105,36918,76,28,77,3,3,364.800000,6536.931505,5487.200000,1,...,0,0,0,0,0,0,0,0,0,0
9106,0,102,5,26,0,9,956.689634,6365.319515,1695.310366,1,...,0,0,0,0,0,0,0,0,0,0
9107,0,153,25,5,0,1,1027.000029,9553.300816,-262.000029,0,...,0,0,0,0,0,0,0,0,0,0
9108,0,109,2,8,0,1,666.042098,8697.912208,205.957902,1,...,0,0,0,0,0,0,0,0,0,0
9109,0,108,23,52,0,1,1254.177129,8119.818403,4361.822871,1,...,0,0,0,0,0,0,0,0,0,0
9110,20090,109,10,59,0,2,523.200000,10643.095391,5907.800000,0,...,0,0,0,0,0,0,0,0,0,0
9111,86631,73,7,44,1,1,400.832857,9779.694013,2811.167143,1,...,0,0,0,0,0,0,0,0,0,0
9112,44019,138,20,60,0,1,165.478147,5745.638718,8114.521853,1,...,0,0,0,0,0,0,0,0,0,0
9113,59367,84,6,48,0,1,6.880385,6869.791652,4025.119615,1,...,0,0,0,0,0,0,0,0,0,0
9114,38874,94,6,86,0,3,331.170924,9834.846406,7752.829076,1,...,0,0,0,0,0,0,0,0,0,0
9115,0,107,12,34,0,2,513.600000,8336.721774,3124.400000,1,...,0,0,0,0,0,0,0,0,0,0
9116,28647,69,11,59,0,3,331.200000,9495.797731,3739.800000,1,...,0,0,0,0,0,0,0,0,0,0
9117,51205,72,4,52,0,2,185.530076,5459.721404,3558.469924,1,...,0,0,0,0,0,0,0,0,0,0
9118,46897,118,13,11,0,3,322.575677,6600.780481,975.424323,1,...,0,0,0,0,0,0,0,0,0,0
9119,56005,68,31,30,1,3,326.400000,8892.235123,1713.600000,0,...,0,0,0,0,0,0,0,0,0,0
9120,0,72,30,69,5,1,518.400000,7891.863355,4449.600000,1,...,0,0,0,0,0,0,0,0,0,0
9121,0,123,5,35,2,1,590.400000,8846.909052,3714.600000,1,...,0,0,0,0,0,0,0,0,0,0
9122,13663,97,1,66,0,2,465.600000,10400.585871,5936.400000,0,...,0,0,0,0,0,0,0,0,0,0
9123,0,76,8,44,0,3,364.800000,7440.534054,2979.200000,0,...,0,0,0,0,0,0,0,0,0,0
9124,60646,134,31,42,0,2,643.200000,6778.017361,4984.800000,1,...,0,0,0,0,0,0,0,0,0,0
9125,0,185,26,35,0,2,1950.725547,10714.506467,4524.274453,1,...,0,0,0,0,0,0,0,0,0,0
9126,0,67,25,21,0,4,482.400000,7540.565301,924.600000,1,...,0,0,0,0,0,0,0,0,0,0
9127,66367,64,6,48,0,3,307.200000,5379.752431,2764.800000,1,...,0,0,0,0,0,0,0,0,0,0
9128,47761,104,16,58,0,1,541.282007,6826.309481,5490.717993,1,...,0,0,0,0,0,0,0,0,0,0
9129,71941,73,18,89,0,2,198.234764,7945.092850,6298.765236,1,...,0,0,0,0,0,0,0,0,0,0
9130,21604,79,14,28,0,1,379.200000,5687.677996,1832.800000,0,...,0,0,0,0,0,0,0,0,0,0
9131,0,85,9,37,3,2,790.784983,7831.418419,2354.215017,1,...,0,0,0,0,0,0,0,0,0,0
9132,21941,96,34,3,0,3,691.200000,9133.568220,-403.200000,1,...,0,0,0,0,0,0,0,0,0,0
9133,0,77,3,90,0,1,369.600000,2611.836866,6560.400000,1,...,0,0,0,0,0,0,0,0,0,0

## Splitting dataset into 2 parts-Development Sample and Validation Sample

In [171]:
X_train, X_test, y_train, y_test = train_test_split(xx, y, test_size=0.2, random_state=0)

In [172]:
regressor = RandomForestRegressor(n_estimators=100, random_state=0,min_samples_split=20)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

## Final MAPE

In [173]:
from sklearn.utils.validation import check_array
def mean_absolute_percentage_error(y_test, y_pred): 
    #y_test, y_pred = check_arrays(y_test, y_pred)
    return np.mean(np.abs((y_test - y_pred) / y_test)) * 100

print(mean_absolute_percentage_error(y_test, y_pred))

9.678602312951895

## Final RMSE

In [174]:
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Root Mean Squared Error: 3523.1689478597928

In [175]:
arr = regressor.feature_importances_

In [176]:
print(arr)

[8.24231548e-03 2.49658380e-01 1.58490866e-02 5.54102532e-03
 3.57641267e-03 5.10567392e-01 1.19737978e-02 4.66959737e-02
 9.93032700e-03 1.18145562e-03 1.25391875e-03 9.49474145e-04
 3.40884891e-04 6.78347566e-04 8.50510326e-04 4.61231445e-04
 4.25739662e-04 8.06284200e-04 1.08726034e-03 9.23461190e-04
 1.95569944e-04 6.41830894e-04 8.82795955e-05 5.28346582e-04
 1.75391340e-03 9.77242181e-04 6.67369703e-04 2.56050108e-04
 6.02951128e-04 1.64428919e-04 5.91031775e-04 1.43949295e-03
 1.04455571e-04 6.04934234e-04 2.16156465e-04 6.28734908e-04
 6.92764742e-04 1.24317898e-03 3.90865188e-04 3.93051216e-04
 1.73957517e-04 4.44987453e-04 9.03455119e-04 2.43499991e-03
 2.03132642e-04 2.77903336e-04 1.93668078e-04 4.98497884e-04
 3.90822011e-04 1.88876872e-04 5.22121569e-04 6.91983979e-04
 3.57702342e-04 5.56071462e-04 2.79836692e-04 3.01059432e-04
 7.16702471e-04 4.41107831e-04 2.14022476e-04 3.79924462e-04
 2.01927764e-04 3.25203799e-04 3.23927124e-04 4.39600288e-05
 1.52296799e-03 1.79866630e-04 4.23047867e-04 1.37121982e-04
 1.09039710e-03 3.17324728e-04 7.84743813e-04 1.45989870e-04
 6.89808704e-04 3.53266633e-04 3.27903354e-04 2.56573729e-04
 5.56469564e-04 1.50048123e-03 3.18235359e-04 1.09470198e-03
 1.08536593e-03 5.04305165e-04 2.19274713e-04 1.75019741e-04
 4.94356118e-04 8.72710831e-04 4.99035026e-04 1.06522146e-03
 7.70022576e-04 3.58220727e-04 3.60985356e-04 4.54105974e-04
 7.17955727e-04 2.92038810e-04 6.33051846e-04 6.20066988e-04
 6.56666175e-04 1.15691708e-03 1.82467533e-04 3.02465535e-04
 4.03452439e-04 1.80205088e-03 1.71349823e-03 6.19925765e-04
 9.63308397e-04 4.80431307e-04 6.80602685e-04 6.17907002e-04
 4.60655045e-04 7.85222706e-04 1.36706241e-04 5.02439313e-04
 1.05469892e-03 1.09272372e-03 4.07892208e-04 8.65015249e-04
 4.34833303e-04 4.15167440e-04 4.20747603e-09 5.64287848e-04
 1.15344738e-04 3.42810577e-05 0.00000000e+00 0.00000000e+00
 1.64452051e-04 2.41111754e-04 1.97197748e-04 3.85047590e-06
 0.00000000e+00 2.86996890e-08 1.97548215e-05 1.29271866e-04
 1.93902551e-04 1.56213295e-05 5.35544863e-07 8.87629547e-05
 6.46860545e-09 0.00000000e+00 3.78846649e-08 2.22736410e-08
 2.55253738e-05 6.66915870e-05 7.03190021e-05 2.31315403e-04
 3.11683082e-04 0.00000000e+00 1.88447562e-04 1.43223675e-04
 5.21343854e-09 0.00000000e+00 5.42876222e-05 1.56230686e-04
 1.24981526e-08 0.00000000e+00 5.99459381e-05 3.93805515e-04
 2.01626672e-08 4.88486720e-06 1.79196469e-04 1.13034184e-03
 1.86108862e-08 3.26614818e-04 0.00000000e+00 6.01794882e-05
 8.72575857e-04 1.17507453e-04 1.86948403e-04 8.52972345e-06
 1.08064247e-05 2.26168160e-06 1.41840009e-04 4.83918992e-05
 5.54195568e-06 1.93409400e-05 5.29563924e-05 7.32553191e-09
 1.34775853e-06 1.02583807e-05 5.42099506e-04 3.31104146e-04
 4.40092501e-08 1.05223181e-04 6.32645736e-05 3.88425353e-04
 3.21657951e-05 3.08807161e-04 4.56058918e-05 3.92757124e-04
 2.10088674e-05 1.39671469e-06 0.00000000e+00 1.51307098e-04
 6.02098224e-09 3.20234066e-09 1.81600021e-04 0.00000000e+00
 1.28498300e-04 0.00000000e+00 1.83048052e-04 1.52252647e-07
 4.96789698e-05 7.27378828e-05 1.92347999e-04 2.04822079e-04
 0.00000000e+00 4.45340702e-06 5.84096763e-09 1.04609689e-04
 2.76188831e-05 6.81106890e-06 2.23845530e-06 2.33884053e-05
 3.35861743e-05 9.08149186e-05 6.68070101e-04 5.38012518e-06
 3.01838772e-05 6.35497047e-05 9.61484517e-05 0.00000000e+00
 2.59898163e-05 2.72244091e-10 7.32853162e-05 1.16284134e-04
 6.71894212e-09 1.94980863e-07 1.69398854e-04 2.11012636e-09
 2.17494775e-08 1.90928450e-04 7.69655952e-05 3.92991810e-04
 3.29347123e-05 7.77577956e-05 8.22833271e-06 2.43671196e-04
 2.86150411e-04 3.68630852e-04 1.11264748e-09 9.61515318e-05
 6.40763378e-09 3.17983789e-05 0.00000000e+00 1.32299583e-04
 0.00000000e+00 6.59639928e-06 1.02187177e-04 3.34324789e-04
 1.58460408e-04 1.04520497e-03 4.96628519e-09 7.59068243e-05
 3.48593764e-08 7.52953399e-05 6.01195250e-05 7.70989573e-05
 5.81351394e-05 4.14387154e-09 0.00000000e+00 3.65299574e-08
 1.36228207e-08 9.09068037e-06 2.12996674e-07 1.15878538e-05
 3.09263722e-03 1.88853289e-04 6.69630779e-08 0.00000000e+00
 2.33239314e-04 4.22508345e-04 0.00000000e+00 2.52157600e-04
 3.40772378e-05 1.23897379e-04 7.50990902e-08 1.51069789e-05
 1.58565522e-05 1.49608519e-04 4.45129002e-07 1.79236344e-04
 2.31521116e-05 1.51968650e-04 7.50988063e-05 1.47111472e-04
 0.00000000e+00 4.14113285e-05 2.83843738e-05 0.00000000e+00
 2.77880898e-04 6.66057050e-05 1.98220450e-05 7.06545063e-04
 0.00000000e+00 1.43108235e-04 4.12797653e-05 1.12213422e-04
 1.02546734e-04 8.48117100e-05 3.65962692e-05 0.00000000e+00
 1.08315645e-07 9.61655557e-05 1.00539707e-04 1.74497041e-04
 5.47764383e-04 3.47124545e-05 0.00000000e+00 3.65873995e-05
 2.83312817e-08 9.06019341e-08 8.65422955e-05 4.95940666e-09
 6.91016001e-06 4.59646107e-06 1.84818097e-04 1.91480919e-05
 2.30633298e-05 1.29592397e-08 1.45147391e-04 5.98830846e-05
 3.05595942e-05 3.62628508e-04 6.06879064e-06 1.43912868e-04
 5.86770343e-08 1.53981509e-03 1.44807443e-05 3.33330096e-08
 3.53092558e-06 1.22630872e-09 4.96638493e-04 1.40778452e-09
 0.00000000e+00 5.72115159e-05 0.00000000e+00 1.28255096e-04
 6.91840314e-05 5.44707304e-09 2.58682655e-08 0.00000000e+00
 0.00000000e+00 1.03831310e-04 2.53158890e-08 2.31545912e-05
 5.53276590e-05 0.00000000e+00 1.04746115e-04 2.46764664e-06
 1.38967777e-05 8.38224941e-05 3.99849393e-04 2.92844139e-05
 1.04643457e-04 1.65913062e-05 0.00000000e+00 1.28890652e-08
 2.77804464e-04 1.73546480e-08 1.83237464e-08 1.66875892e-05
 1.13473546e-08 3.76226717e-06 0.00000000e+00 3.01116363e-04
 1.39107419e-06 1.34320177e-08 5.63503418e-09 2.18690786e-04
 1.46599649e-06 6.47779881e-06 4.52470001e-05 2.21419539e-04
 5.20296999e-05 3.38495757e-05 7.75625258e-06 1.89885877e-08
 8.43396622e-06 1.74417516e-03 3.91383514e-05 1.19542501e-04
 8.66826890e-06 3.23625709e-08 1.42334177e-08 7.28758593e-08
 1.72606031e-06 1.26063997e-03 2.46981173e-04 3.92271496e-08
 3.69150605e-04 1.27351458e-04 1.14837531e-04 1.85242719e-04
 5.47394362e-04 2.43278757e-04 4.83230799e-06 4.43494000e-05
 1.41778255e-04 0.00000000e+00 1.60526098e-04 3.09731202e-10
 9.36823195e-05 1.16767778e-04 7.00070181e-05 1.04049241e-06
 2.54895360e-04 9.02168742e-11 7.77679501e-05 8.39395428e-05
 2.04202995e-04 9.38797685e-09 2.14011843e-04 1.09482052e-04
 0.00000000e+00 1.26006014e-05 3.16449068e-05 1.01772711e-05
 6.01428317e-05 5.29539997e-05 5.60276982e-04 2.41498837e-06
 1.86336324e-04 5.53294822e-04 1.02848870e-08 2.38738408e-04
 7.47887979e-04 2.51773103e-10 4.70796720e-04 6.37007233e-09
 4.76607207e-05 6.94610337e-05 0.00000000e+00 1.61662136e-06
 7.84927308e-06 0.00000000e+00 1.88709851e-09 1.17187836e-04
 1.06800048e-07 2.22085640e-10 1.88161891e-07 1.62297786e-04
 4.67780066e-07 6.19232504e-06 1.87872245e-04 1.32157254e-04
 4.31984235e-06 9.38808404e-05 7.27818947e-09 1.22164019e-04
 2.11108081e-04 3.58993630e-05 0.00000000e+00 0.00000000e+00
 1.28461891e-07 1.00251856e-03 4.92473407e-05 3.37052870e-09
 2.94572124e-04 1.08156460e-05 9.31155104e-05 1.48565468e-04
 2.13920541e-04 2.03458683e-04 1.77732355e-09 0.00000000e+00
 1.74491624e-09 0.00000000e+00 0.00000000e+00 1.13594442e-08
 3.56751923e-04 3.09705007e-04 2.97337161e-09 2.70008533e-05
 9.74438451e-09 3.29033524e-05 4.72844238e-09 1.29181465e-04
 1.41654215e-05 4.14934435e-08 1.42343641e-04 2.31421427e-05
 1.42993540e-09 0.00000000e+00 8.85289569e-05 1.50571537e-03
 8.05026584e-08 4.70641178e-09 0.00000000e+00 8.13411973e-06
 8.43169604e-05 2.01857338e-04 1.79226960e-08 2.87685242e-08
 1.46727187e-05 0.00000000e+00 5.25705748e-04 1.11717860e-05
 4.71872000e-05 3.02171921e-08 5.14002567e-04 0.00000000e+00
 6.56803809e-04 2.76104106e-05 2.25184493e-04 2.47781332e-10
 9.92743286e-06 4.09667462e-04 1.61995623e-04 2.65351049e-08
 1.50266705e-04 3.07033565e-05 0.00000000e+00 1.49756326e-06
 3.33099429e-06 0.00000000e+00 1.49369258e-05 4.82467182e-05
 4.81124385e-05 8.30155370e-06 0.00000000e+00 5.75614185e-06
 1.74123295e-05 1.45362511e-08 1.80243442e-05 7.61568593e-04
 2.41683691e-09 3.75201397e-07 1.29051497e-04 3.47477709e-04
 8.15839819e-06 7.33568679e-10 2.92807401e-06 0.00000000e+00
 5.85947161e-06 2.71622696e-09 4.81647058e-05 9.32333539e-09
 1.01351398e-04 2.57334740e-07 0.00000000e+00 4.09809077e-05
 3.83745408e-04 7.98085568e-05 1.42479469e-05 4.14312738e-05
 1.13779325e-05 6.05436435e-05 0.00000000e+00 1.10058783e-04
 0.00000000e+00 1.08810340e-05 1.79713295e-07 1.48205692e-09
 2.24332577e-09 1.13352214e-04 8.16904652e-05 2.80210411e-08
 3.25263373e-05 3.82043774e-05 1.30844744e-07 1.17215341e-06
 1.74714757e-04 0.00000000e+00 7.16396068e-09 1.21363512e-04
 1.67684070e-08 4.28195609e-07 8.11270512e-07 5.23575700e-09
 8.24115737e-04 9.94278395e-06 2.96640472e-09 1.93440191e-05
 3.41631980e-04 1.78498821e-04 3.73215154e-05 1.07495109e-04
 1.52500109e-04 7.98850729e-05 9.28940985e-05 0.00000000e+00
 0.00000000e+00 3.07341338e-04 2.41050928e-05 2.03064819e-04
 2.50136543e-09 5.18992852e-05 0.00000000e+00 3.34698682e-04
 3.44506578e-04 1.73694096e-04 4.08932264e-09 6.17602444e-05
 2.22816963e-04 1.75437072e-09 8.37366099e-06 2.04805493e-05
 1.72323610e-03 2.03133587e-09 8.97822210e-06 4.73495439e-08
 6.21161726e-09 5.32450834e-09 3.57768407e-04 1.98539612e-04
 3.90349587e-05 0.00000000e+00 6.89431101e-09 8.06701925e-05
 7.23994657e-05 1.08158301e-08 1.07792880e-04 1.45718066e-04
 4.98626667e-05 0.00000000e+00 2.45331628e-05 5.47817049e-04
 1.54195631e-06 0.00000000e+00 6.69974080e-05 1.27745424e-04
 7.38228968e-10 6.07750997e-06 7.82793307e-06 1.40193675e-08
 5.55206362e-04 1.30050376e-04 2.20106045e-04 1.29968434e-06
 1.12053790e-09 9.24639851e-06 1.36883936e-04 9.09438924e-05
 2.61330151e-04 1.80555273e-04 1.08179504e-08 1.11868177e-04
 5.32697737e-07 5.55289278e-09 4.40825880e-04 0.00000000e+00
 6.02980895e-05 8.24472323e-09 2.35644044e-07 1.71305832e-05
 0.00000000e+00 1.30135970e-04 1.32773533e-04 4.42234655e-06
 3.52219700e-05 0.00000000e+00 6.92709177e-06 2.17717841e-06
 2.90660871e-09 6.68252215e-05 9.92748220e-07 3.14395872e-05
 9.90159266e-05 0.00000000e+00 3.24085455e-05 8.99725895e-08
 5.98508141e-06 8.73468754e-06 2.31939878e-09 6.96061356e-06
 7.37480878e-05 7.55590735e-05 1.72348590e-06 2.69116545e-04
 2.06979274e-07 3.81882791e-04 0.00000000e+00 3.78114822e-09
 2.58975353e-04 8.25712256e-05 1.64359526e-04 3.66856931e-05
 2.77915078e-05 0.00000000e+00 1.51448287e-08 2.11677876e-08
 1.64119906e-05 1.11132002e-05 1.35641323e-08 1.26029688e-04
 1.78431238e-08 1.07739823e-09 1.72824470e-04 0.00000000e+00
 1.48116558e-04 9.48469592e-06 1.03629324e-06 0.00000000e+00
 3.13797410e-04 3.82140514e-09 8.60408162e-09 9.48062305e-05
 2.56966830e-06 3.53941796e-04 3.22233542e-08 0.00000000e+00
 0.00000000e+00 2.17823638e-04 8.85626770e-05 5.64690625e-05
 5.58731694e-04 2.50701077e-04 1.23096056e-04 8.95045449e-09
 4.77850581e-05 1.32010458e-08 1.53624039e-08 1.05799524e-04
 1.68788153e-04 2.31431685e-04 3.03425168e-05 1.07510570e-08
 1.60517733e-04 4.19387279e-06 9.50934448e-09 5.82423793e-09
 1.67880645e-09 1.56280002e-04 7.98515757e-05 3.95085178e-08
 1.52855592e-04 1.09487758e-07 8.87627775e-08 2.30874334e-05
 8.31077695e-10 9.48476877e-08 3.24280972e-09 8.27524337e-05
 4.52441079e-04 2.39331723e-08 8.48423571e-06 7.00672642e-09
 7.00867568e-05 1.95063455e-05 3.05905539e-06 7.74105571e-06
 8.21883673e-05 2.46321244e-05 0.00000000e+00 3.48550099e-07
 0.00000000e+00 6.58493208e-04 6.06988407e-04 2.89057279e-04
 1.07438645e-04 3.33306194e-04 0.00000000e+00 4.34234592e-05
 3.12938785e-05 1.37426070e-04 6.74046250e-05 1.42216507e-04
 0.00000000e+00 2.29772622e-04 5.22693457e-05 3.06500018e-04
 3.44171698e-05 2.83921333e-09 1.04419650e-09 3.64056562e-06
 2.47942641e-04 3.33532552e-05 1.78687766e-08 3.44663076e-10
 1.02468551e-08 1.10581616e-06 4.78354907e-04 1.40630361e-04
 5.35968615e-09 2.27929448e-04 8.05833533e-05 1.42188775e-08
 4.64882406e-09 2.18158536e-06 0.00000000e+00 1.77429053e-05
 1.24341373e-06 3.68617951e-05 1.05953342e-08 3.72755383e-04
 3.17368719e-06 6.21885730e-05 7.01320036e-10 2.10315833e-04
 5.77927062e-05 2.87542576e-05 1.45054147e-05 6.16946810e-06
 0.00000000e+00 2.73939291e-05 1.94480595e-04]

In [177]:
np.shape(X_train)

(7307, 795)